### PR TITLE
Fix a test - CLI messages are changed

### PR DESCRIPTION
**Pull request by ihcomega56**
Follow the change of https://github.com/pyrsia/pyrsia/pull/1448

### CODE REVIEW

**Comment by ihcomega56** [comment]
https://github.com/pyrsia/pyrsia/pull/1448 should be merged for success of integration tests.

**Review by fishseabowl — APPROVED** [review]

**Comment by dasmanas** [comment]
@ihcomega56 change is very straight forward but why Integration test run is failing?

**Comment by ihcomega56** [comment]
@dasmanas In a test case for `build status`, we had used `"` (double quotations) as a delimiter for `awk` command before ([code](https://github.com/pyrsia/pyrsia-integration-tests/blob/7f1ea7193332079d4078f51dba78dbb9291ace93/bats/tests/pyrsia_node_docker_build_service.bats#L54)) to extract build id from a CLI response. It would be changed to `'` (single quotations) and the extraction would be failed, which cause the failure of integration tests. So the delimiter has to be changed as well.

before
```
Build status for '2ddc2c77-b95b-481c-bde1-2d480bd321aa' is 'SUCCESS' 
```

after
```
Build status for '2ddc2c77-b95b-481c-bde1-2d480bd321aa' is 'SUCCESS' 
```

**Comment by ihcomega56** [comment]
@dasmanas Oh I was misunderstanding. That is because Pyrsia repo in not merged to main yet.

**Pull request merged**
